{% set version = "20210223" %}
{% set name = "eclib" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/JohnCremona/eclib/archive/v{{ version }}.tar.gz
  sha256: e9133eb2ff60cc8d083b0c9af15cae04a3376951806ecbd127a41362f4097f3a

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('eclib', max_pin='x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - libtool
    - automake
    - make
  host:
    - pari
    - ntl
    - libflint
    - mpfr
    - gmp
    - gf2x
  run:
    - {{ pin_compatible('pari') }}
    - ntl
    - libflint
    - mpfr
    - gmp
    - gf2x

test:
  commands:
    - test -f ${PREFIX}/include/eclib/arith.h
    - test -f ${PREFIX}/lib/libec.a
    - test -f ${PREFIX}/lib/libec.dylib     # [osx]
    - test -f ${PREFIX}/lib/libec.so        # [linux]

about:
  home: https://github.com/JohnCremona/eclib
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: |
    The eclib package includes mwrank (for 2-descent on elliptic curves over Q) and
    modular symbol code used to create the elliptic curve database.
  dev_url: https://github.com/JohnCremona/eclib

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
